--auto generated by sql scriptor


SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[App_Temp_Data]') AND type in (N'U'))
BEGIN
	PRINT '=> CREATE TABLE App_Temp_Data'
	
	CREATE TABLE [dbo].[App_Temp_Data](
		[RID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[DATA] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[CREATE_AT] [datetime] NOT NULL,
	 CONSTRAINT [PK_Session_App_Temp_Data] PRIMARY KEY CLUSTERED 
	(
		[RID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_Session_App_Temp_Data_CREATE_AT]') AND type = 'D')
BEGIN
	ALTER TABLE [dbo].[App_Temp_Data] ADD  CONSTRAINT [DF_Session_App_Temp_Data_CREATE_AT]  DEFAULT (getdate()) FOR [CREATE_AT]
END

GO

IF OBJECT_ID('App_Company', 'U') IS NULL
BEGIN
	PRINT '=> CREATE TABLE App_Company'
	
    CREATE TABLE [dbo].[App_Company](
	    [RID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	    [Company_Code] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	    [Company_Name_CN] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	    [Company_Name_EN] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
    ) ON [PRIMARY]
END
GO

IF OBJECT_ID('App_User_Language', 'U') IS NULL
BEGIN
	PRINT '=> CREATE TABLE App_User_Language'
	
    CREATE TABLE [dbo].[App_User_Language](
	    [RID] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_App_User_Language_RID]  DEFAULT (newid()),
	    [User_ID] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	    [LanguageID] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	    [CompanyCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
     CONSTRAINT [PK_App_User_Language] PRIMARY KEY CLUSTERED
    (
	    [User_ID] ASC,
	    [LanguageID] ASC
    )WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
    ) ON [PRIMARY]
END
GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[App_Item_Language]') AND type in (N'U'))
BEGIN
	PRINT '=> CREATE TABLE App_Item_Language'
	
	CREATE TABLE [dbo].[App_Item_Language](
		[ItemID] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
		[Description1] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Description2] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Description3] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Description4] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
		[Description5] [nvarchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	 CONSTRAINT [PK_App_Item_Language] PRIMARY KEY CLUSTERED 
	(
		[ItemID] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

GO

SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[App_Web_Log]') AND type in (N'U'))
BEGIN
	PRINT '=> CREATE TABLE App_Web_Log'
	
	CREATE TABLE [dbo].[App_Web_Log] (
		  [id] [int] IDENTITY(1,1) NOT NULL,
		  [application] [nvarchar](50) NOT NULL,
		  [logged] [datetime] NOT NULL,	  
		  [level] [nvarchar](50) NOT NULL,
		  [message] [nvarchar](max) NOT NULL,
		  [username] [nvarchar](256) NULL,
		  [request_ip] [nvarchar](256) null,
		  [session] [nvarchar](max) null,
		  [cookie] [nvarchar](max) null,
		  [user_agent] [nvarchar](max) null,
		  [request_method] [varchar](50) null,
		  [url] [nvarchar](max) NULL,
		  [query_string] [nvarchar](MAX) NULL,
		  [query_form] [nvarchar](MAX) null,
		  [logger] [nvarchar](250) NULL,
		  [callsite] [nvarchar](max) NULL,      
		  [exception] [nvarchar](max) NULL,
		  [stack_trace] [nvarchar](max) NULL,
		  [api_action] [varchar](256) NULL,
		  [sql_text] [nvarchar](MAX) null,
		  [elapsed_seconds] [float] NULL,
		  [start_time] [datetime] NULL,
		  [end_time] [datetime] NULL
		CONSTRAINT [PK_App_Web_Log] PRIMARY KEY CLUSTERED ([Id] ASC)
		  WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
END

GO

PRINT 'Update PROCEDURE: [SP_ItemLanguage]'

IF Object_ID(N'[SP_ItemLanguage]', N'P') IS NOT NULL
	DROP PROCEDURE [SP_ItemLanguage]
GO

/*
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Purpose		: 
Date		: 11/21/2013
Author		: Button Lin
Note		:
-----------------------------------------------------
11/21/2013		Button Lin   the first version
	the latest update: 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/

CREATE PROCEDURE [dbo].[SP_ItemLanguage] (
    @ItemID NVARCHAR(300) = NULL
    ,@Description1 NVARCHAR(300) = NULL
    ,@Description2 NVARCHAR(300) = NULL
    ,@Description3 NVARCHAR(300) = NULL
	,@Description4 NVARCHAR(300) = NULL
	,@Description5 NVARCHAR(300) = NULL
    ,@actionID VARCHAR(10) = ''
    ,@actionType TINYINT = 50 -- 10:新增(Add)/20:修改(update)/30:删除(Delete)/50: 查询(Select ALL)/70:查询(select by key)
    )
AS
SET NOCOUNT ON

IF @actionType = 10
BEGIN
    IF NOT EXISTS (
            SELECT *
            FROM App_Item_Language
            WHERE (
                    1 = 1
                    AND [ItemID] = @ItemID
                    )
            )
    BEGIN
        INSERT INTO App_Item_Language (
            [ItemID]
            ,[Description1]
            ,[Description2]
            ,[Description3]
			,[Description4]
			,[Description5]
            )
        SELECT @ItemID
            ,@Description1
            ,@Description2
            ,@Description3
			,@Description4
			,@Description5
    END
END

IF @actionType = 20
BEGIN
    IF EXISTS (
            SELECT *
            FROM App_Item_Language
            WHERE (
                    1 = 1
                    AND [ItemID] = @ItemID
                    )
            )
    BEGIN
        UPDATE App_Item_Language
        SET [ItemID] = @ItemID
            ,[Description1] = @Description1
            ,[Description2] = @Description2
            ,[Description3] = @Description3
			,[Description4] = @Description4
			,[Description5] = @Description5
        WHERE (
                1 = 1
                AND [ItemID] = @ItemID
                )
    END
END

IF @actionType = 30
BEGIN
    IF EXISTS (
            SELECT *
            FROM App_Item_Language
            WHERE (
                    1 = 1
                    AND [ItemID] = @ItemID
                    )
            )
    BEGIN
        DELETE
        FROM App_Item_Language
        WHERE (
                1 = 1
                AND [ItemID] = @ItemID
                )
    END
END

IF @actionType = 50
BEGIN
    SELECT *
    FROM App_Item_Language
END

IF @actionType = 70
BEGIN
    SELECT *
    FROM App_Item_Language
    WHERE (
            1 = 1
            AND [ItemID] = @ItemID
            )
END

IF @actionType = 80
BEGIN
    SELECT *
    FROM App_Item_Language
    WHERE ItemID LIKE @ItemID + '%'
END

GO

