//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS424.src.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class App_Temp_Data :ICloneable, ITable
    {
    	public object Clone() 
        { 
            return this.MemberwiseClone(); 
        } 
    
                    
        public string RID { get; set; }
                    
        public string DATA { get; set; }
                    
        public System.DateTime CREATE_AT { get; set; }
    }
}
