//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS424.src.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost_Per :ICloneable, ITable
    {
    	public object Clone() 
        { 
            return this.MemberwiseClone(); 
        } 
    
                    
        public string RID { get; set; }
                    
        public string Sect_RID { get; set; }
                    
        public string Emp_No { get; set; }
                    
        public System.DateTime Effect_Date { get; set; }
                    
        public string Customer_id { get; set; }
                    
        public decimal Cost_Ratio { get; set; }
    }
}
